package scgf.api.funcionario.model;

public enum Especialidade {
    PROGRAMACAO,
    ENGENHARIA_DA_COMPUTACAO,
    ENGENHARIA_CIVIL,
    ENGENHARIA_ELETRICA,
    ENGENHARIA_MECANICA,
    MEDICINA,
    PSICOLOGIA,
    PEDAGOGIA,
    ADMINISTRACAO,
    ADVOCACIA,
    JUIZ_DIREITO,
    TEC_INFORMATICA,
    TEC_REFRIGERACAO,
    TEC_ENFERMAGEM
}
